
skip_prefixes:
  - 'Merge '
  - 'BREAKING: '
type_rules:
  - type: feat
    description: 表示在代码库中新增了一个功能，这和语义化版本中的 [`MINOR`](https://semver.org/#summary) 相对应.
  - type: fix
    description: 在代码库中修复了一个 `bug`，这和语义化版本中的 [`PATCH`](https://semver.org/#summary) 相对应.
  - type: perf
    description: 对当前实现进行改进，提升性能的代码修改.
  - type: docs
    description: 仅文档的修改(`documentation`）.
  - type: style
    description: 不影响代码含义的代码修改（空格，格式化，缺少分号，等等）.
  - type: refactor
    description: 既不是修复 `bug` 也不是新增功能的代码修改.
  - type: test
    description: 添加缺少的「单元测试」，或更正已存在的「单元测试」.
  - type: build
    description: 用于更新构建配置、开发工具或其他与用户无关的更改.
  - type: chore
    description: 对构建过程或辅助工具和依赖库的更改（如自动文档生成工具、CI 构建工具，配置和脚本）.
reference: https://github.com/donglf681/go-commitlinter#description
style_pattern: '[a-z]+'
style_doc: 类型和范围应始终为小写.
scope_pattern: '(feat|fix|perf|docs|style|refactor|test|build|chore)'
scope_doc: <scope> 可以为空（例如，如果更改是全局的或难以分配给单个组件），在这种情况下省略括号.
subject_pattern: "^[a-z\\p{Han}]\\w*"
subject_doc: <subject> 首字母小写.
