name: 'Go pull request message linter'
description: 'Inspect pull request messages with the format "<type>(scope): <subject>".'
runs:
  using: 'composite'
  steps:
    - run: |
        curl -Lo go-commitlinter.tar.gz https://github.com/donglf681/go-commitlinter/releases/download/0.1.0/go-commitlinter_0.1.0_Linux_x86_64.tar.gz
        tar xvfz go-commitlinter.tar.gz
        mv go-commitlinter /usr/local/bin/
      shell: bash
    - run: echo $TITLE | go-commitlinter
      shell: bash
